@startuml TP2

title Diagrama de Clases Cajú

hide circle
skinparam classAttributeIconSize 0
skinparam roundcorner 25
skinparam sequenceArrowThickness 2
skinparam classFontSize 20

skinparam class {
BackgroundColor FloralWhite
ArrowColor DimGray
BorderColor DimGray
}

class Panel{
       - pregunta: Pregunta
       - jugadores: HashMap<String, Jugador>
       - fabricaPreguntas: FabricaPreguntas
       + crearPregunta(String, String, set<Steing>
       + crearJugador(String)
       + hacerPregunta(String, set<String>)
       + usarDuplicador(String)
       + usarTriplicador(String)
       + pedirPuntos(String): Int
}

class FabricaPreguntas{
       + crearPregunta(String, String, set<String>): Pregunta
}

class Jugador{
        - nombre: String
        - puntos: Int
        - multiplicador: Multiplicador
        - duplicadorDisponible: boolean
        - triplicadorDisponible: boolean
        + Jugador(String)
        + pedirPuntos(): Int
        + estadoDuplicador()
        + estadoTriplicador()
        + asignarPuntos(Int)
}

abstract class Pregunta{
        - opcionesCorrectas: Collection<String>
        - textoPregunta: String
        + compararRespuestas(): Int
        + usarMultiplicador()
}

class PreguntaClasica{
        + PreguntaClasica(String, Collection<String>)
        + compararRespuestas(Collection<String>): Int
}

class PreguntaConPenalidad{
        + PreguntaConPenalidad(String, set<String>)
        + compararRespuestas(Collection<String>): Integer
        + usarMultiplicador()
}

class PreguntaConPuntajeParcial{
        + PreguntaConPuntajeParcial(String, set<String>)
        + compararRespuestas(Collection<String>): Int
}

interface Multiplicador{
        - multiplicar(Int): Int
}

class Unplicador{
        - multiplicar(Int): Int
}

class Duplicador{
        - multiplicar(Int): Int
}

class Triplicador{
        - multiplicar(Int): Int
}

Panel o-->"1..*" Jugador
Panel o--"1--*" Pregunta
Panel o-left->"1" FabricaPreguntas
FabricaPreguntas ..> Pregunta
PreguntaClasica -up-|> Pregunta
PreguntaConPenalidad -up-|> Pregunta
PreguntaConPuntajeParcial -up-|> Pregunta
Unplicador .up.|> Multiplicador
Duplicador .up.|> Multiplicador
Triplicador .up.|> Multiplicador
Jugador o-->"1" Multiplicador
PreguntaConPenalidad ..> Multiplicador

@enduml