@startuml TP2
hide circle
skinparam classAttributeIconSize 0
skinparam roundcorner 25
skinparam sequenceArrowThickness 2
skinparam classFontSize 20

skinparam class {
BackgroundColor FloralWhite
ArrowColor DimGray
BorderColor DimGray
}

class Jugador{
        - Nombre
        - Puntaje
        + crearJugador(String):Jugador
        + Responder() : respuesta
        + asignarPuntos()
}

class Panel{
       - preguntas
       - jugadores 
       + crearJugador(String):Jugador   
       + crearPregunta(String, Respuesta): Pregunta
       + mostrarPregunta()
       + PedirRespuesta()
       + pasarRespuesta(respuestas)
       + asignarPuntaje()
}

class PreguntaVerdaderoFalso{
        - respuestaVerdadera
        - respuestaFalsa
        - textoPregunta 
        + crear()
        + responder()
        + mostrarPregunta()
        + crearPregunta(String, Respuesta): Pregunta
        + compararRespuesta(respuesta) : Puntos   
}

interface Respuesta{
        - respuesta
        + =()
}
class RespuestaCorrecta{
}

class RespuestaIncorrecta{ 
}

' class Turno{
        
' }

Panel o-right-> Jugador
Panel o-down-> PreguntaVerdaderoFalso
RespuestaCorrecta .up.|> Respuesta
RespuestaIncorrecta .up.|> Respuesta
PreguntaVerdaderoFalso *-right-> Respuesta
Jugador ...> Respuesta

@enduml