@startuml

activate panel

panel -> pregunta: crearPreguntaVoFClasica
activate pregunta
pregunta --> panel: Pregunta

panel -> jugadores: crearJugador
activate jugadores
jugadores --> panel: Jugadores


panel -> jugadores: pedirRespuesta
jugadores --> panel: respuesta


panel -> pregunta: chequearRespuesta
pregunta --> panel: puntos

deactivate pregunta

panel -> jugadores: asignarPuntos

deactivate jugadores

@enduml