@startuml TP2

title Entrega 0

hide circle
skinparam classAttributeIconSize 0
skinparam roundcorner 25
skinparam sequenceArrowThickness 2
skinparam classFontSize 20

skinparam class {
BackgroundColor FloralWhite
ArrowColor DimGray
BorderColor DimGray
}

class Panel{
       - preguntas: ArrayList<Pregunta>
       - jugadores: ArrayList<Jugador>
       - fabricaPreguntas : FabricaPreguntas
       + crearPregunta(String, String, ArrayList<Boolean>)
       + pasarPregunta() : String
       + hacerPregunta()
       + crearJugador(String)
       + pedirPuntos(): ArrayList
}

class Jugador{
        - nombre: String
        - puntos: Int
        + responder(Respuesta, HashMap)
        + predirPuntos(): Int
}


class Pregunta{
        - respuesta: Boolean
        - textoPregunta: String
        + pasarPregunta(): String
        + hacerPregunta()
}

interface CalculadorPuntaje{
        +calcular(Map, Map)
}

class CalculadorPuntajeClasico{
        +calcular(Map, Map)
}

class CalculadorPuntajeConPenalidad{
        +calcular(Map, Map)
}

class CalculadorPuntajeParcial{
        +calcular(Map, Map)
}

class FabricaPreguntas{
        +crearPregunta(String, String, ArrayList) : Pregunta
}

class PreguntaMCClasica{
        +PreguntaMCClasica(String, ArrayList)
}

class PreguntaMCConPenalidad{
        +PreguntaMCConPenalidad(String, ArrayList)
}

class PreguntaMCConPuntajeParcial{
        +PreguntaMCConPuntajeParcial(String, ArrayList)
}

class PreguntaVoFClasica{
        +PreguntaVoFClasica(String, ArrayList)
}

class PreguntaVoFConPenalidad{
        +PreguntaVoFConPenalidad(String, ArrayList)
}

interface Respuesta{
        +responder(HashMap)
}

class RespuestaClasica{
        -respuestas : HashMap
        +RespuestaClasica(ArrayList)
        +responder(HashMap) : Int
}

class RespuestaConPenalidad{
        -respuestas : HashMap
        +RespuestaConPenalidad(ArrayList)
        +responder(HashMap) : Int
}

class RespuestaConPuntajeParcial{
        -respuestas : HashMap
        +RespuestaConPuntajeParcial(ArrayList)
        +responder(HashMap) : Int
}

Panel o-down->"2" Jugador
Panel o-->"1..*" Pregunta
Panel o-->"1" FabricaPreguntas
Pregunta o-up-> Respuesta
Pregunta ..> Jugador
Respuesta ..> CalculadorPuntaje
CalculadorPuntajeClasico ..|> CalculadorPuntaje
CalculadorPuntajeConPenalidad ..|> CalculadorPuntaje
CalculadorPuntajeParcial ..|> CalculadorPuntaje
PreguntaMCClasica -up-|> Pregunta
PreguntaMCConPenalidad -up-|> Pregunta
PreguntaMCConPuntajeParcial -up-|> Pregunta
PreguntaVoFClasica -up-|> Pregunta
PreguntaVoFConPenalidad -up-|> Pregunta
RespuestaClasica ..|> Respuesta
RespuestaConPenalidad ..|> Respuesta
RespuestaConPuntajeParcial ..|> Respuesta


@enduml