@startuml TP2

title Diagrama de secuencia para la creación de preguntas

hide footbox
skinparam backgroundColor white

skinparam sequence {
ArrowColor DimGray
ActorBorderColor DodgerBlue
LifeLineBorderColor Navy
LifeLineBackgroundColor CornflowerBlue
ParticipantBorderColor LighSlateGray
ParticipantBackgroundColor CornflowerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF
ActorBackgroundColor mintCream
ActorFontColor CornflowerBlue
ActorFontSize 17
ActorFontName Aapex
}

actor TestCase
activate TestCase

create LectorPreguntas
TestCase -> LectorPreguntas : new()
activate LectorPreguntas

create FabricaDePreguntas
LectorPreguntas -> FabricaDePreguntas :  new()
activate FabricaDePreguntas

create Panel
TestCase -> Panel : Panel(LectorPreguntas)
activate Panel
Panel -> LectorPreguntas: parsearPreguntas()
loop por pregunta en archivo
LectorPreguntas -> FabricaDePreguntas : crearPregunta(String, String, String[], String[], List<Grupo>)
create Pregunta
FabricaDePreguntas -> Pregunta: new(String, String, String[], Collection<String>, Map<String, String>)
activate Pregunta
create Comportamiento
Pregunta -> Comportamiento: new()
activate Comportamiento
Pregunta --> FabricaDePreguntas: Pregunta
FabricaDePreguntas -->LectorPreguntas: Pregunta
end loop
LectorPreguntas -> Panel: List<Pregunta>

deactivate Pregunta
deactivate FabricaDePreguntas
deactivate Panel
deactivate TestCase

@enduml