@startuml TP2

title Diagrama de secuencia para la creación de preguntas

hide footbox
skinparam backgroundColor white

skinparam sequence {
ArrowColor DimGray
ActorBorderColor DodgerBlue
LifeLineBorderColor Navy
LifeLineBackgroundColor CornflowerBlue
ParticipantBorderColor LighSlateGray
ParticipantBackgroundColor CornflowerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF
ActorBackgroundColor mintCream
ActorFontColor CornflowerBlue
ActorFontSize 17
ActorFontName Aapex
}

actor TestCase
activate TestCase

participant ":Panel" as Panel
create Panel
TestCase -> Panel : new()
activate Panel

participant ":FabricaDePreguntas" as FabricaDePreguntas
create FabricaDePreguntas
Panel -> FabricaDePreguntas :  new()
activate FabricaDePreguntas
FabricaDePreguntas --> Panel : FabricaDePreguntas

TestCase -> Panel : crearPregunta(String, String, Set<String>)

Panel -> FabricaDePreguntas : crearPregunta(String, String, Set<String>)

FabricaDePreguntas -> Pregunta: new()
activate Pregunta
Pregunta --> FabricaDePreguntas: Pregunta
FabricaDePreguntas --> Panel: Pregunta

deactivate Pregunta
deactivate FabricaDePreguntas
deactivate Panel
deactivate TestCase

@enduml