@startuml

title Diagrama de secuencia para pregunta Clasica. Salta excepción al usar Multiplicador.

hide footbox
skinparam backgroundColor white

skinparam sequence {
ArrowColor DimGray
ActorBorderColor DodgerBlue
LifeLineBorderColor Navy
LifeLineBackgroundColor CornflowerBlue
ParticipantBorderColor LighSlateGray
ParticipantBackgroundColor CornflowerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF
ActorBackgroundColor mintCream
ActorFontColor CornflowerBlue
ActorFontSize 17
ActorFontName Aapex
}

actor TestCase
activate TestCase

participant ":Panel" as Panel
create Panel
TestCase -> Panel : new()
activate Panel

TestCase -> Panel : crearPregunta(String, String, Set<String>, Set<String>)



create PreguntaClasica
Panel -> PreguntaClasica : crearPregunta(String, String, Collection<String>, Collection<String>)
activate PreguntaClasica

TestCase -> Panel: crearJugadores(String, String)
create Jugador
Panel -> Jugador: new(String)
activate Jugador
Jugador --> Panel: JugadorActual
Panel -> Jugador: new(String)
Jugador --> Panel: JugadorSiguiente

TestCase -> Panel: activarTriplicador()
Panel -> PreguntaClasica: activarMultiplicador()
PreguntaClasica -> Panel : ExcepcionSoloPreguntaConPenalidadPuedeUsarMultiplicador()

deactivate PreguntaClasica
deactivate Jugador
deactivate Panel
deactivate TestCase

@enduml