@startuml

title Diagrama de secuencia para preguntas con penalidad

hide footbox
skinparam backgroundColor white

skinparam sequence {
ArrowColor DimGray
ActorBorderColor DodgerBlue
LifeLineBorderColor Navy
LifeLineBackgroundColor CornflowerBlue
ParticipantBorderColor LighSlateGray
ParticipantBackgroundColor CornflowerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF
ActorBackgroundColor mintCream
ActorFontColor CornflowerBlue
ActorFontSize 17
ActorFontName Aapex
}

actor TestCase
activate TestCase

participant ":Panel" as Panel
create Panel
TestCase -> Panel : new()
activate Panel

participant ":FabricaDePreguntas" as FabricaDePreguntas
create FabricaDePreguntas
Panel -> FabricaDePreguntas :  new()
activate FabricaDePreguntas
FabricaDePreguntas --> Panel : FabricaDePreguntas

TestCase -> Panel : crearPregunta(String, String, Set<String>)

Panel -> FabricaDePreguntas : crearPregunta(String, String, Set<String>)

FabricaDePreguntas -> PreguntaConPenalidad: new()
activate PreguntaConPenalidad
PreguntaConPenalidad --> FabricaDePreguntas: PreguntaConPenalidad
FabricaDePreguntas --> Panel: PreguntaConPenalidad

TestCase -> Panel: crearJugador(String)
Panel -> Jugador: new(String)
activate Jugador
Jugador --> Panel: Jugador

TestCase -> Panel: hacerPregunta(String, Set<String>)
Panel -> PreguntaConPenalidad: compararRespuestas(Collection<String>)
PreguntaConPenalidad --> Panel: Int
Panel -> PreguntaConPenalidad: usarMultiplicador(Jugador, Int): Int
PreguntaConPenalidad -> Jugador: multiplicarPuntos(Int)
Jugador --> PreguntaConPenalidad: Int
PreguntaConPenalidad --> Panel: Int
Panel -> Jugador: asignarPuntos(Int)


deactivate PreguntaConPenalidad
deactivate Jugador
deactivate FabricaDePreguntas
deactivate Panel
deactivate TestCase

@enduml