@startuml

hide footbox
skinparam backgroundColor white

skinparam sequence {
ArrowColor DimGray
ActorBorderColor DodgerBlue
LifeLineBorderColor Navy
LifeLineBackgroundColor CornflowerBlue
ParticipantBorderColor LighSlateGray
ParticipantBackgroundColor CornflowerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF
ActorBackgroundColor mintCream
ActorFontColor CornflowerBlue
ActorFontSize 17
ActorFontName Aapex
}

actor TestCase
activate TestCase

participant ":Panel" as Panel
create Panel

TestCase -> Panel : new()
activate Panel

TestCase -> Panel : crearPreguntaVOFClasica(String)

participant ":LectorDeArchivos" as Lector
create Lector
Panel -> Lector : new(String)

activate Lector

loop
Lector -> Pregunta : new(String, boolean)
activate Pregunta
Pregunta --> Lector : unaPregunta : Pregunta
end

deactivate Pregunta
Lector --> Panel : preguntas : ArrayList <Pregunta>
deactivate Lector

loop 2 veces
TestCase -> Panel : crearJugador()
Panel -> Jugadores : new()
activate Jugadores
Jugadores --> Panel : unJugador : Jugador
deactivate Jugadores
end

loop 2 veces
TestCase -> Panel : pedirRespuestas()
Panel -> Jugadores : responder()
activate Jugadores
Jugadores --> Panel : unMensaje : boolean
deactivate Jugadores
end

TestCase -> Panel : chequearRespuestas(ArrayList)
Panel -> Pregunta : chequearRespuesta()
activate Pregunta
Pregunta --> Panel : unMensaje : boolean
deactivate Pregunta

TestCase -> Panel : asignarPuntos()

loop 2 veces
Panel -> Jugadores : asignarPuntos()
activate Jugadores
Jugadores -> Jugadores : puntos++
activate Jugadores
deactivate Jugadores
deactivate Jugadores
end

deactivate Panel
deactivate TestCase

@enduml